openapi: 3.0.0
servers: []
info:
  description: This is an API that recieves requests for   immediate rides and schedules for a ride-share app
  version: "1.0.0"
  title: Simple Ride-share API
  contact:
    email: wgreen16@my.bcit.ca
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: request
    description: requested sent about a ride
paths:
  /requests/ride-order:
    post:
      tags:
        - request
      summary: immediatetly searches for a ride
      operationId: app.order_ride_immediately
      description: makes an order for the best possible ride for the user
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RideOrder'
        description: Reading item to add
        
  /requests/schedule-order:
    post:
      tags:
        - request
      summary: searches for a relevant schedule
      operationId: app.schedule_ride
      description: makes a request for the ride schedule of the coming days
      responses:
        '201':
          description: item created
        '400':
          description: 'invalid input, object invalid'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleOrder'
        description: Reading item to add
    
components:
  schemas:
    RideOrder:
      type: object
      required:
        - user_id
        - order_time
        - starting_point
        - destination
        - max_passenger
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        order_time:
          type: string
          format: date-time
          example: "2022-01-19T14:20:00.001Z"
        starting_point:
          type: string
          example: '123 Granville St'
        destination:
          type: string
          example: '123 Londsdale Ave'
        max_passenger:
          type: integer
          example: 3
        
    ScheduleOrder:
      required:
        - user_id
        - order_time
        - interval_start
        - interval_end
        - destination
      properties:
        user_id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        order_time:
          type: string
          format: date-time
          example: '2022-01-19T14:20:00.001Z'
        interval_start:
          type: string
          format: date-time
          example: '2022-01-19T14:20:00.001Z'
        interval_end:
          type: string
          format: date-time
          example: '2022-01-19T14:20:00.001Z'
        destination:
          type: string
          example: '123 Lonsdale ave'
        # trace_id:
        #   type: string
        #   format: uuid
        #   example: b2aa8e1f-6bea-46b5-a388-09892bc26edf
      type: object